# Site settings
title: Dustin McQuay
email: dmcquay@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Dustin McQuay. I write mostly about programming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dmcquay.github.io" # the base hostname & protocol for your site
twitter_username: dustinmcquay
github_username: dmcquay
highlighter: pygments

# Build settings
markdown: kramdown
